### ISSUE TITLE
missing actor : Yayoi Dock

### ISSUE THREAD

**Issue by LIONKANZENTAI** [0ADMods/yayoi_japan#1]
ERROR: art/meshes/structural/yayoi_dock.dae: Exception caught while parsing a COLLADA document from file.

ERROR: Could not load mesh 'art/meshes/structural/yayoi_dock.dae'

ERROR: CObjectEntry::BuildVariation(): Model art/meshes/structural/yayoi_dock.dae failed to load

ERROR: Error loading object variation (actor: art/actors/structures/yayoi/dock.xml)

ERROR: art/meshes/structural/yayoi_dock.dae: Exception caught while parsing a COLLADA document from file.

ERROR: Could not load mesh 'art/meshes/structural/yayoi_dock.dae'

ERROR: CObjectEntry::BuildVariation(): Model art/meshes/structural/yayoi_dock.dae failed to load

ERROR: Error loading object variation (actor: art/actors/structures/yayoi/dock.xm

**Comment by JustusAvramenko** [comment]
Fixed by commit 348bee60c4766192115a8cda8eba06c0ac1559e8
